package Selenium.All_Pactice;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class JavaScriptExecutor {

	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Win-10\\Desktop\\Java\\Eclipse\\chromedriver.exe");
		WebDriver driver=new ChromeDriver();

		driver.get("https://demoqa.com/automation-practice-form");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(20));
		
		//declaration
		JavascriptExecutor js=(JavascriptExecutor)driver;
		
		
		//method to refresh browser
		Thread.sleep(2000);
		js.executeScript("location.reload();");
		Thread.sleep(2000);
		js.executeScript("history.go(0);");
		
		//method to scroll to particular element on webpage
		Thread.sleep(2000);
		js.executeScript("arguments[0].scrollIntoView(true);", driver.findElement(By.xpath("//h1[text()=\"Practice Form\"]")));
		
		//method to return domain name of web page
		Thread.sleep(2000);
		String domain=js.executeScript("return document.domain;").toString();	
		System.out.println(domain);
		
		//method to return web page url
		Thread.sleep(2000);
		String url=js.executeScript("return document.URL;").toString();	
		System.out.println(url);
		
		//method to return web page title
		Thread.sleep(2000);
		String title=js.executeScript("return document.title;").toString();	
		System.out.println(title);
		
		//method to click
		WebElement w=driver.findElement(By.xpath("//input[@placeholder='First Name']"));
		js.executeScript("arguments[0].click();", w);
		
		//method to send text
		Thread.sleep(2000);
		js.executeScript("document.getElementById('firstName').value='Pranav';");
		
		//method to scroll till end of web page
		Thread.sleep(2000);
		js.executeScript("window.scrollBy(0,document.body.scrollHeight)");
		
		//method to genarate Alert window
		js.executeScript("alert('This alert is generated by JavascriptExecutor...');");
		
		//method to oad another web page
		Thread.sleep(2000);
		js.executeScript("window.location = 'https://www.softwaretestingmaterial.com' ");
	}

}
